### ISSUE TITLE
Feature #1-User can create a profile

### ISSUE THREAD

**Issue by AndyPark20** [AndyPark20/code-journal#1]
## 💰 Motivation

Users like to personalize things! 😄

## 📐 Plan

Create a responsive form for users to enter their profile details into and save their data to local storage.

## 🖼️ Wireframe

![user can create a profile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-create-a-profile.png)

## ✅ Task List

- [ ] Pick a nice font pair from Google Fonts for headings and body text.
- [ ] Pick a nice accent color.
- [ ] Create a simple, polished header in HTML and CSS that shows the name of the application.
- [ ] Create a simple, polished form in the HTML and CSS that shows a placeholder image for the avatar.
- [ ] Apply fonts to the heading, labels, and form inputs.
- [ ] Check to make sure that the form looks good on mobile and desktop.
- [ ] Make all form inputs `required`.
- [ ] Make the `name` attributes of the form input elements match the keys of the profile data model.
- [ ] Listen for `'input'` events on the avatar url input.
- [ ] Update the avatar preview image's `src` when the avatar url input changes.
- [ ] Listen for `'submit'` events on the form.
- [ ] Assign all of the form's values into the profile data model when the form is submitted.
- [ ] Reset the form inputs when the form is submitted.
- [ ] Reset the avatar preview image when the form is submitted.
- [ ] Make sure that the user's data is persisted to local storage between reloads.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again.
